version: "3.9"
services:
  grpc-stock-trading-server:
    build:
      context: .
      dockerfile: grpc-stock-trading-server/Dockerfile
    container_name: grpc-stock-trading-server
    env_file:
      - .env.docker
    ports:
      - "9091:9090"  # gRPC
#      - "9400:9400"  # Prometheus metrics
    networks:
      - trading-net

  grpc-stock-trading-client:
    build:
      context: .
      dockerfile: grpc-stock-trading-client/Dockerfile
    container_name: grpc-stock-trading-client
    environment:
      - SERVER_HOST=grpc-stock-trading-server
      - SERVER_PORT=9090
    depends_on:
      - grpc-stock-trading-server
    ports:
      - "8085:8085"
#      - "9401:9401"    # Prometheus metrics
    networks:
      - trading-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9095:9090"
    networks:
      - trading-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # set admin password
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"  # Grafana UI
    depends_on:
      - prometheus
    networks:
      - trading-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  trading-net:
    driver: bridge
